import { Poppins, Roboto } from "next/font/google";
import "./styles/globals.css";


const poppins = Poppins({
  weight: "400", // Make sure you use a valid weight
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "400", // Make sure you use a valid weight
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${roboto.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
